import streamlit as st
import pandas as pd
from single_game.optimizer import LineupOptimizer

st.set_page_config(page_title="FanTeam Single-Game Lineup Optimizer", layout="wide")

st.title("⚽ FanTeam Single-Game Lineup Optimizer")
st.write("Generate customized, mathematically optimized tournament lineups using real-time market data expectations.")

# --- SIDEBAR DYNAMIC CONTROLS ---
st.sidebar.header("Optimizer Settings")

# 1. Adjustable Budget Slider
budget = st.sidebar.slider("Salary Cap Budget", min_value=70.0, max_value=120.0, value=100.0, step=0.5)

# 2. Maximum Players Allowed per Team Slider
max_players = st.sidebar.slider("Maximum Players per Club", min_value=1, max_value=7, value=5, step=1)

# 3. Match Status Filters
status_mode = st.sidebar.radio("Player Availability Filter", ["All", "Expected", "Starting"])

# 4. Smart Anti-Correlation Toggle
anti_corr = st.sidebar.checkbox("Apply Goalkeeper Anti-Correlation", value=True, 
                                help="Enforcing this ensures the optimizer never drafts an opposing Forward against your chosen Goalkeeper.")

# --- DATA SESSION HANDLING ---
# This ensures we use the projection output generated by your data pipeline engine
if "player_projections" in st.session_state and st.session_state["player_projections"] is not None:
    df_pool = st.session_state["player_projections"]
    
    st.subheader(f"Available Player Pool ({len(df_pool)} players imported)")
    st.dataframe(df_pool.style.format({"Salary": "{:.2f}", "Projected_xPts": "{:.2f}"}), use_container_width=True)
    
    # Trigger Optimization Build
    if st.button("🚀 Calculate Optimal Lineup", type="primary"):
        optimizer_engine = LineupOptimizer()
        
        optimized_lineup, logs_msg = optimizer_engine.optimize(
            df=df_pool,
            salary_cap=budget,
            max_per_team=max_players,
            roster_status_filter=status_mode,
            use_correlation=anti_corr
        )
        
        if optimized_lineup is not None:
            st.success(logs_msg)
            
            # Metric Summary Cards
            total_cost = optimized_lineup["Salary"].sum()
            total_pts = optimized_lineup["Projected_xPts"].sum()
            
            col1, col2, col3 = st.columns(3)
            col1.metric("Projected Lineup Points", f"{total_pts:.2f} xPts")
            col2.metric("Total Lineup Cost", f"{total_cost:.2f}M / {budget:.2f}M")
            col3.metric("Roster Composition", f"{len(optimized_lineup)} / 11 Players")
            
            # Render Final Table Structure
            st.subheader("📋 Your Optimized Lineup")
            st.dataframe(optimized_lineup[["Player", "Position", "Team", "Salary", "Projected_xPts"]], use_container_width=True)
        else:
            st.error(logs_msg)
            
else:
    st.info("💡 Please run the live data injection pipeline first on the home or configuration panel to load the player market pool metrics into memory.")